### ISSUE TITLE
Last week / Last month

### ISSUE THREAD

**Issue by jon-dennis** [w-martin/git-quality#3]
"Weekly" view is no much more useful that "Monthly". Would be better to show more recent information in more details

**Comment by w-martin** [comment]
Thanks for the feature request! 1 week seems to be a bit too recent for the PR graphs, considering that only one branch can be summarised - so this would only include merged PRs, for a multi-branch repo. However, I've implemented 12mo, 6mo, 3mo and 1mo for comparison
